## numpy basics
Phase1

In [2]:
import numpy as np 

In [3]:
arr_1d= np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d= np.array([[1,2,3], [4,5,6], [7,8,9]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs numpy array

In [7]:
py_list = [1,2,3]
print("Python list multiplication:", py_list*2)
np_array = np.array([1,2,3]) #element wise multiplication
print("Numpy array multiplication:", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Time taken for Python list:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) *2
print("Time taken for Numpy array:", time.time() - start)

Python list multiplication: [1, 2, 3, 1, 2, 3]
Numpy array multiplication: [2 4 6]
Time taken for Python list: 0.11646103858947754
Time taken for Numpy array: 0.01038980484008789


## creating array from scratch

In [13]:
zeros = np.zeros((3,4))
print("array of zeros: \n", zeros)

ones = np.ones((2,5))
print("array of ones: \n", ones)

full = np.full((2,2), 7)
print("array filled with 7: \n", full)

random = np.random.random((2,3))
print("array of random numbers: \n", random)

sequence = np.arange(0, 12, 2)
print("array with sequence from 0 to 10 with step of 2: \n", sequence)

array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array of ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
array filled with 7: 
 [[7 7]
 [7 7]]
array of random numbers: 
 [[8.14614225e-03 7.51381625e-02 4.16948777e-04]
 [1.69497051e-03 2.38456245e-01 7.72365673e-01]]
array with sequence from 0 to 10 with step of 2: 
 [ 0  2  4  6  8 10]


### vector, Matrix and tensor

In [14]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Prop

In [16]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("shape of array:", arr.shape)
print("Dimensions:", arr.ndim)
print("DType:", arr.dtype)

shape of array: (3, 3)
Dimensions: 2
DType: int64


## Array reshaping

In [24]:
array = np.arange(12)
print("original:",array)

reshaped = array.reshape((3,4))
print("reshaped to 3x4:\n", reshaped)

flattened = reshaped.flatten()
print("flattened:\n", flattened)

raveled = reshaped.ravel() #ravel ( returns view,instead of copy)
print("raveled:\n", raveled)

#Transpose
transpose = reshaped.T
print("Transposed:\n", transpose)


original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
